title: Soumya Kasuganti # your name (or website title) here
# logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Hi. I'm a designer and (sometimes) educator. I am currently cooking a lot and cutting my own hair.
  <br><br>

theme: jekyll-theme-minimal
